### PR TITLE
Support nested arrays

### LINKED ISSUE #6: Add support for non-empty array default values in the Readme
Related to https://github.com/bitnami/charts/pull/7007.

The Readme-generator does not have support to include in the README the Arrays default values when needed. For example, the field `master.disableCommands` in the Redis chart, appears with default value `[]`, when it should be `[FLUSHDB, FLUSHALL]`.

I consider this information not trivial, and therefore should be included in the Readme generator.

As a suggestion, we could add a flag similar to `@skip` or `[array]`, that replaced the default value with a message recommending to `Check the values.yaml` when the array is too big to be displayed in the Readme table.

### LINKED ISSUE #11: Adding modifier to some param in array item breaks metadata validation
Hi,

it seems like adding modifier to array item key breaks metadata validation. Here is minimal example:

```yaml
## @section Jobs definition

## Jobs definition
##
jobs:
  -
    ## @param jobs[0].nameOverride String to partially override jobs.names.fullname
    ##
    nameOverride: ""
    ## @param jobs[0].fullnameOverride String to fully override jobs.names.fullname
    ##
    fullnameOverride: ""
    ## @param jobs[0].resources.limits The resources limits override for the Job
    ##
    resources:
      limits: {}
```

Above works fine, but generates `undefined` for `jobs[0].resources.limits`:
```
### Jobs definition

| Name                       | Description                                      | Value       |
| -------------------------- | ------------------------------------------------ | ----------- |
| `jobs[0].nameOverride`     | String to partially override jobs.names.fullname | `""`        |
| `jobs[0].fullnameOverride` | String to fully override jobs.names.fullname     | `""`        |
| `jobs[0].resources.limits` | The resources limits override for the Job        | `undefined` |
```

So, lets annotate `jobs[0].resources.limits` with [object] modifier:
```yaml
## @section Jobs definition

## Jobs definition
##
jobs:
  -
    ## @param jobs[0].nameOverride String to partially override jobs.names.fullname
    ##
    nameOverride: ""
    ## @param jobs[0].fullnameOverride String to fully override jobs.names.fullname
    ##
    fullnameOverride: ""
    ## @param jobs[0].resources.limits [object] The resources limits override for the Job
    ##
    resources:
      limits: {}
```

This however breaks metadata validation:
```bash
❯ npx readme-generator -v values2.yaml -r README.md
Skipping check for jobs[0].nameOverride
Skipping check for jobs[0].fullnameOverride
Skipping check for jobs[0].resources.limits
INFO: Checking missing metadata...

######
The following errors must be fixed before proceeding
######

ERROR: Metadata provided for non existing key: jobs[0].nameOverride
ERROR: Metadata provided for non existing key: jobs[0].fullnameOverride
ERROR: Metadata provided for non existing key: jobs[0].resources.limits
ERROR: Wrong metadata!
```

Generally I am trying to document quite a big and complicated array element. Is it a recommended way to do it with `[0]` in parameter's path or is there more generic way?
Thanks.

### PR DESCRIPTION
**Pull request by miguelaeh**
**Description of the change**

**Benefits**
This PR contains the following:
- Support for nested arrays properties.
- Set by default the array content for plain arrays instead of empty arrays. (Arrays with just strings)
- Pretty print metadata to make it easy to develop and check changes

**Possible drawbacks**

**Applicable issues**

  - fixes #6
  - fixes #11 

**Additional information**

**Checklist**

- [x] Version bumped in `package.json` and `package-lock.json` according to [semver](http://semver.org/).
- [x] New features are documented in the README.md
- [x] New features contain a new test at the `tests` folder
- [x] All tests pass running `npm test`

### CODE REVIEW

**Comment by carrodher** [comment]
Great changes! Just one un-related suggestion:

How do you see about having a way to obtain the version from the binary? It seems there is not an option for that, I tried `readme-generator version` and `readme-generator --version` without luck, in the same way it is not listed as a valid argument:
```console
$ readme-generator --help
Usage: readme-generator [options]

Options:
  -v, --values <path>    Path to the values.yaml file
  -r, --readme <path>    Path to the README.md file
  -c, --config <path>    Path to the config file
  -m, --metadata <path>  Path for the metadata output file
  -h, --help             display help for command
```

It is useful for the kind of change you are implementing in this PR, in this way users can see if they are using a specific version that should contain those changes or not.

**Comment by carrodher** [comment]
Apart from that, there is an [alert](https://github.com/bitnami-labs/readme-generator-for-helm/security/dependabot/package-lock.json/set-value/open) about an issue in one dependency, can you take a look?

**Comment by miguelaeh** [comment]
Hi!
The version suggestion is un-related so we can handle it in a new PR.

About the dependency vulnerability, right now there are two reported, I checked them but since they are dependencies of dependencies we cannot update them until the real dependency is updated.

**Comment by miguelaeh** [comment]
Tested at https://github.com/bitnami/charts/pull/7614

**Pull request merged**
